apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "simple-backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      # deployment.metadata.neme
      name: "simple-backend"
  template:
    metadata:
      labels:
        # deployment.metadata.neme
        name: "simple-backend"
        # serviceMesh need: app version
        app: "simple-backend"
        version: ""
    spec:
      containers:
        - image: "{{ DEPLOY_IMAGE }}"
          imagePullPolicy: "Always"
          name: "master"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"